### ISSUE TITLE
Brew Cask Broken

### ISSUE THREAD

**Issue by colindunn** [dewdrop-org/Client-Mac#10]
Hi there,

The brew cask for this client is broken due to http://dewdrop.dangelov.com not being available.
Do you want the cask to continue, or should it be removed?

**Comment by dangelov** [comment]
Hi,

I'm actually shutting this project down and I've started by shutting down the domain for it a couple of days ago. Had no idea it has a brew cask :)

I'm still using it personally, but since I've never found the time to work on improving it for public use, thought it's better to shut down. Going to delete the repos and associated info in a few days too, so please remove the brew cask.

**Comment by colindunn** [comment]
Thanks for the feedback. Removing the cask. https://github.com/caskroom/homebrew-cask/pull/29616
